#! /bin/sh 

# enable MiniTV to show bootlogo in display. Will be switched to desired usermode once E2 starts.
#echo 1 > /proc/stb/lcd/mode

echo "gbx3" > /proc/stb/info/gbmodel

# ZRAM TEST
# mem_by_cpu=$(($(grep MemTotal /proc/meminfo | awk ' { print $2 } ')*256))
# modprobe zram num_devices=1
# echo $mem_by_cpu > /sys/block/zram0/disksize 
# mkswap /dev/zram0
# swapon /dev/zram0

#touch /dev/dbox/lcd0
