#!/bin/sh
### BEGIN INIT INFO
# Provides:           oem-info
# Required-Start:     $local_fs
# Required-Stop:      $local_fs
# Default-Start:      S
# Default-Stop:
# Short-Description:  change enigma.info on the fly for oem build
### END INIT INFO

if [ -f "/.oem-info" ]; then
  exit
fi

# default build info
#displaymodel=ET7x00

INFO="/usr/lib/enigma.info"

CHIP=`cat /proc/stb/info/chipset`
if [ $CHIP == "bcm73625" ]; then
  sed -i -e 's:displaymodel=ET7x00:displaymodel=ET7100 V2:' $INFO
else
  sed -i -e 's:displaymodel=ET7x00:displaymodel=ET7000:' $INFO
fi

sed -i '/checksum=/d' $INFO
printf "checksum=%s\n" $(md5sum $INFO | cut -d ' ' -f 1) >> $INFO
touch "/.oem-info"
