#!/bin/sh

# ----- CONFIGURATION -----

LINE="--------------------------------------"
TRANSMISSION_ON=0
NAME="transmission-daemon"
DAEMON="/usr/bin/nice -n 9 /usr/bin/transmission-daemon"
DIRECTORY="/hdd/transmission"
RPC_PORT=9091
DOWNLOAD_DIR="/hdd/transmission/download"
CONFIG_DIR="/hdd/transmission/config"
WATCH_DIR="/hdd/transmission/watch"
USER="root"
PASSWORD="dreambox"
ARGS="-c $WATCH_DIR -g $CONFIG_DIR -a *.*.*.* -w $DOWNLOAD_DIR -p $RPC_PORT -t -u $USER -v $PASSWORD"
INET_ADDR=`awk '/address/{print$2}' /etc/network/interfaces`
PATH=/usr/sbin:/usr/bin:/sbin:/bin
TRANSMISSION_WEB_HOME="/usr/share/transmission/web/"

# ----- END OF CONFIGURATION -----

if [ ! -d $DIRECTORY ] ; then mkdir $DIRECTORY; fi
if [ ! -d $DOWNLOAD_DIR ] ; then mkdir $DOWNLOAD_DIR; fi
if [ ! -d $CONFIG_DIR ] ; then mkdir $CONFIG_DIR; fi
if [ ! -d $WATCH_DIR ] ; then mkdir $WATCH_DIR; fi


case $1 in
	start)
		echo -n "starting $NAME... "
		echo
		start-stop-daemon -S -b -n $NAME -a $DAEMON -- $ARGS 
		sleep 2
		echo
		echo $LINE
		echo "Transmission Started !!!"
		echo "Open your browser at http://$INET_ADDR:9091"
		echo $LINE
		echo
	;;
        stop)
		echo
		echo -n "stopping $NAME... "
		killall $NAME
		echo "done."
	;;
	restart)
		echo
		echo -n "restarting $NAME... "
		$0 stop
		sleep 5
		$0 start
		echo
	;;
        autostart | enable)
		echo
        	update-rc.d transmissiond defaults 99
		sleep 2
		echo
	;;
        noautostart | disable)
		echo
        	update-rc.d -f transmissiond remove
		sleep 2
		echo
	;;

	*)
	echo " "
	echo "Options: $0 {start|restart|stop|enable|disable}"
	echo " "
esac

exit 0
