#!/bin/sh

if ! grep -q devtmpfs /proc/mounts; then
        if grep -q devtmpfs /proc/filesystems; then
                mount -t devtmpfs devtmpfs /dev
        else
                mount -t tmpfs tmpfs /dev  -o size=64k,mode=0755
                rm /dev/null
                mknod /dev/null c 1 3
                mkdir /dev/pts /dev/shm
                mount -t devpts devpts /dev/pts
        fi
fi

echo > /dev/mdev.seq

echo "/sbin/mdev" >/proc/sys/kernel/hotplug

touch /dev/.udev

[ -d "/sys/kernel" ] || mount sysfs /sys -t sysfs
[ -L "/dev/fd" ] || ln -sf /proc/self/fd /dev/fd
[ -e /dev/pts ] || mkdir -m 0755 /dev/pts
[ -e /dev/shm ] || mkdir -m 1777 /dev/shm
mount -t devpts devpts /dev/pts

mdev -s
