#!/bin/sh

check_online() {
    count=0
    while [ $count -lt 5 ]; do
        sleep 0.5
# No point in pinging by-name to test whether the network is up as that
# requires the network to be up to resolve the name!!
#   So instead ping a known DNS server address.
#   Possible ipv4/ipv6 choices (May 2022) are:
# Google:
#       8.8.8.8 or 2001:4860:4860::8888
# Quad9
#       9.9.9.9 or 2620:fe::fe:9
# Cloudfare
#       1.1.1.1 or 2606:4700:4700::1111
#
# Only send 1 packet (-c) and only wait for 3s (-W)
        if ping -4 -c 1 -W 3 8.8.8.8 >/dev/null 2>&1 ||
           ping -6 -c 1 -W 3 2001:4860:4860::8888 >/dev/null 2>&1; then
            return 0
        fi
        count=$((count+1))
    done
    echo "Network not up"
    exit 1
}

check_online

if [[ "$@" ]]; then
    POOL=$1
else
    POOL=`sed -En 's|config\.misc\.NTPserver=(.+)|\1|p' /etc/enigma2/settings`
    if [ -z "$POOL" ]; then
        POOL="pool.ntp.org"
    fi
fi

/usr/sbin/ntpd -nq -p $POOL

exit $?
