FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"
PRINC = "3"

SRC_URI_append_et4x00 = " file://0001-v4l2-fix-build-with-recent-kernels-the-v4l2_buffer-i.patch"
SRC_URI_append_et5x00 = " file://0001-v4l2-fix-build-with-recent-kernels-the-v4l2_buffer-i.patch"
SRC_URI_append_et6x00 = " file://0001-v4l2-fix-build-with-recent-kernels-the-v4l2_buffer-i.patch"
SRC_URI_append_et9x00 = " file://0001-v4l2-fix-build-with-recent-kernels-the-v4l2_buffer-i.patch"
SRC_URI_append_odinm7 = " file://0001-v4l2-fix-build-with-recent-kernels-the-v4l2_buffer-i.patch"
SRC_URI_append_odinm9 = " file://0001-v4l2-fix-build-with-recent-kernels-the-v4l2_buffer-i.patch"
SRC_URI_append_ventonhde = " file://0001-v4l2-fix-build-with-recent-kernels-the-v4l2_buffer-i.patch"
SRC_URI_append_ventonhdx = " file://0001-v4l2-fix-build-with-recent-kernels-the-v4l2_buffer-i.patch"
