--- a/Makefile	2019-06-14 19:10:00.689989294 +0200
+++ b/Makefile	2019-06-14 19:10:16.574013912 +0200
@@ -3,7 +3,7 @@
 ###############################################################################
 
 # Set the compiler being used.
-CXX = $(CXXPREFIX)g++$(CXXSUFFIX)
+#CXX = $(CXXPREFIX)g++$(CXXSUFFIX)
 
 # Includes needed for proper compilation
 INCLUDES +=
