# MACHINEBUILDS: zgemmah8se
#@TYPE: Machine
#@NAME: h9
#@DESCRIPTION: Machine configuration for the h8se

SOC_FAMILY = "hisi3798mv200"
HICHIPSET = "3798mv200"
VER = "-v2"

RCTYPE = "28"
RCNAME = "zgemma3"

MTD_KERNEL = "mtd8"
MTD_ROOTFS = "mtd9"
KERNEL_FILE = "uImage"
ROOTFS_FILE = "rootfs.ubi"

IMAGE_CLASSES += " zgemma-yaffs_image"
IMAGE_FSTYPES += "ubi zgemmayaffs"

MKUBIFS_ARGS = "-m 4096 -e 253952 -c 2048"
UBINIZE_ARGS = "-m 4096 -p 256KiB -s 4096"

MACHINE_FEATURES += " ubimb chkrootmb hisil-3798mv200 mali blindscan-dvbs dvb-c skins1080 multitranscoding kodi22 himedia no-subssupport adwol emmc hbbtv-browser-webkit"

EXTRA_OECONF:append:pn-enigma2 = " --with-alphablendingacceleration=always --with-blitaccelerationthreshold=250  --with-fillaccelerationthreshold=190000"

require conf/machine/include/airdigital-hisil-3798mv200.inc
require conf/machine/include/airdigial-ubi-yaffs.inc

BBMASK = "meta-vuplus/recipes-graphics/"
BBMASK += "meta-vuplus/recipes-webkit/"

