# MACHINEBUILDS: zgemmai55plus
#@TYPE: Machine
#@NAME: i55Plus
#@DESCRIPTION: Machine configuration for the i55Plus

SOC_FAMILY = "hisi3798mv200"
HICHIPSET = "3798mv200"
VER = "-v2"

RCTYPE = "25"
RCNAME = "zgemma8"

MTD_KERNEL = "mtd6"
MTD_ROOTFS = "mtd7"
KERNEL_FILE = "uImage"
ROOTFS_FILE = "rootfs.ubi"

IMAGE_FSTYPES += "ubi"

MKUBIFS_ARGS = "-m 2048 -e 126976 -c 8192"
UBINIZE_ARGS = "-m 2048 -p 128KiB"

MACHINE_FEATURES += " ubimb chkrootmb emmc hisil-3798mv200 mali skins1080 multitranscoding kodi22 himedia no-subssupport dvbc-only adwol"

MACHINE_EXTRA_RDEPENDS = "\
    enigma2-plugin-extensions-gbipboxclient \
    enigma2-plugin-systemplugins-satipclient \
"

EXTRA_OECONF:append:pn-enigma2 = " --with-alphablendingacceleration=always --with-blitaccelerationthreshold=250  --with-fillaccelerationthreshold=190000"

require conf/machine/include/airdigital-hisil-3798mv200.inc
require conf/machine/include/airdigital-ubi.inc

BBMASK = "meta-vuplus/recipes-graphics/"
BBMASK += "meta-vuplus/recipes-webkit/"

