#! /bin/sh 

echo "gbultra" > /proc/stb/info/gbmodel

# ZRAM TEST
# mem_by_cpu=$(($(grep MemTotal /proc/meminfo | awk ' { print $2 } ')*256))
# modprobe zram num_devices=1
# echo $mem_by_cpu > /sys/block/zram0/disksize 
# mkswap /dev/zram0
# swapon /dev/zram0

touch /dev/dbox/lcd0
