#! /bin/sh
### BEGIN INIT INFO
# Provides:          urandom
# Required-Start:    $local_fs $time
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Save and restore random seed between restarts.
# Description:       This script saves the random seed between restarts.
#                    It is called from the boot, halt and reboot scripts.
### END INIT INFO

test -c /dev/urandom || exit 0

RANDOM_SEED_FILE=/var/lib/urandom/random-seed

. /etc/default/rcS
[ -f /etc/default/urandom ] && . /etc/default/urandom

case "$1" in
	start|"")
		test "$VERBOSE" != no && echo "Initializing random number generator..."
		# Load and then save 512 bytes, which is the size of the entropy
		# pool. Also load the current date, in case the seed file is
		# empty.
		( date +%s.%N; [ -f "$RANDOM_SEED_FILE" ] && cat "$RANDOM_SEED_FILE" ) \
			>/dev/urandom
		rm -f "$RANDOM_SEED_FILE"
		umask 077
		dd if=/dev/urandom of=$RANDOM_SEED_FILE count=1 \
			>/dev/null 2>&1 || echo "urandom start: failed."
		umask 022
		;;
	stop)
		# Carry a random seed from shut-down to start-up;
		# see documentation in linux/drivers/char/random.c
		test "$VERBOSE" != no && echo "Saving random seed..."
		umask 077
		dd if=/dev/urandom of=$RANDOM_SEED_FILE count=1 \
			>/dev/null 2>&1 || echo "urandom stop: failed."
		;;
	*)
		echo "Usage: urandom {start|stop}" >&2
		exit 1
		;;
esac

exit 0
