#!/bin/bash

check () {
	smbd=/usr/sbin/smbd
	test -x "$smbd" || exit 0
	nmbd=/usr/sbin/nmbd
	test -x "$nmbd" || exit 0
}

enabled () {
	grep -qE '^microsoft-ds' /etc/inetd.conf && return 0
	return 1
}

disabled () {
	grep -qE '^#microsoft-ds' /etc/inetd.conf && return 0
	return 1
}

enable () {
	check
	echo -n "Starting Samba "
	sed -i 's/^#\(microsoft-ds\|netbios-ns\|netbios-dgm\|netbios-ssn\)/\1/g' /etc/inetd.conf
	/etc/init.d/inetd.busybox restart >/dev/null
	echo "."
}

disable () {
	echo -n "Stopping Samba "
	sed -i 's/^\(microsoft-ds\|netbios-ns\|netbios-dgm\|netbios-ssn\)/#\1/g' /etc/inetd.conf
	/etc/init.d/inetd.busybox restart >/dev/null
	killall -15 nmbd smbd >/dev/null 2>&1
	echo "."
}



case "$1" in
	start)
		enabled && exit 0
		enable
		;;
	stop)
		disabled && exit 0
		disable
		;;
	reload|force-reload)
		check
		start-stop-daemon --stop --quiet --signal 1 --exec $smbd
		start-stop-daemon --stop --quiet --signal 1 --exec $nmbd
		;;
	restart)
		enabled && disable
		echo ""
		echo -n "Waiting for samba processes to die off"
		for i in 1 2 3 ;
		do
			sleep 1
			echo -n "."
		done
		echo ""
		enable
		;;
	*)
		echo "Usage: /etc/init.d/samba {start|stop|reload|restart|force-reload}"
		exit 1
esac

exit 0
