#!/bin/sh
### BEGIN INIT INFO
# Provides:           oem-info
# Required-Start:     $local_fs
# Required-Stop:      $local_fs
# Default-Start:      S
# Default-Stop:
# Short-Description:  change enigma.info on the fly for oem build
### END INIT INFO

if [ -f "/.oem-info" ]; then
  exit
fi

# default build info
#displaybrand=UNiBOX
#displaymodel=HD-x
#model=inihdx

#displaybrand=GI
#displaymodel=LX-x
#model=inihde

INFO="/usr/lib/enigma.info"

TYPE=`cat /proc/stb/info/boxtype`
BRAND=`cat /proc/enigma/displaybrand`
VERSION=`cat /proc/stb/fp/version`
if [ $BRAND == "UNiBOX" ]; then
  if [ $TYPE == "ini-3000" ]; then
    sed -i -e 's:displaymodel=HD-x:displaymodel=HD-1:' $INFO
    sed -i -e 's:model=inihdx:model=uniboxhd1:' $INFO
  elif [ $TYPE == "ini-5000" ]; then
    sed -i -e 's:displaymodel=HD-x:displaymodel=HD-2:' $INFO
    sed -i -e 's:model=inihdx:model=uniboxhd2:' $INFO
    sed -i -e 's:rcname=ini0:model=rcname=ini1:' $INFO
  elif [ $TYPE == "ini-7000" ]; then
    sed -i -e 's:displaymodel=HD-x:displaymodel=HD-3:' $INFO
    sed -i -e 's:model=inihdx:model=uniboxhd3:' $INFO
    sed -i -e 's:rcname=ini0:model=rcname=ini1:' $INFO
  elif [ $TYPE == "ini-7012" ]; then
    sed -i -e 's:displaymodel=HD-x:displaymodel=HD-3:' $INFO
    sed -i -e 's:model=inihdx:model=uniboxhd3:' $INFO
  fi
elif [ $BRAND == "GI" ]; then
  if [ $TYPE == "ini-1000lx" ]; then
    sed -i -e 's:displaymodel=LX-x:displaymodel=LX-2T:' $INFO
    sed -i -e 's:model=inihde:model=xpeedlx2t:' $INFO
  elif [ $TYPE == "ini-1000de" ]; then
    if [ $VERSION == "2" ]; then
      sed -i -e 's:model=inihde:model=xpeedlx2:' $INFO
    else
      sed -i -e 's:model=inihde:model=xpeedlx1:' $INFO
    fi
  fi
fi

sed -i '/checksum=/d' $INFO
printf "checksum=%s\n" $(md5sum $INFO | cut -d ' ' -f 1) >> $INFO
touch "/.oem-info"
