#!/bin/sh
set -e

start() {
    FACTOR=50
    [ -f /etc/default/zram ] && source /etc/default/zram || true
    factor=$FACTOR # percentage
    memtotal=$(grep MemTotal /proc/meminfo | awk ' { print $2 } ')
    mem_by_cpu=$(($memtotal*$factor/100*1024))
   	echo 1 > /sys/block/zram0/reset
   	echo $mem_by_cpu > /sys/block/zram0/disksize
	mkswap /dev/zram0
	swapon /dev/zram0
}

stop() {
    swapoff /dev/zram0 || true
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
