#!/bin/sh
### BEGIN INIT INFO
# Provides:          waitfordhcp
# Required-Start:    $network
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Wait for DHCP before softcams
### END INIT INFO

case "$1" in
    start)
        echo "Starting wait-for-dhcp..."
        /usr/bin/wait_for_dhcp.sh &
        ;;
    stop)
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

