#!/bin/sh
### BEGIN INIT INFO
# Provides:          waitfordhcp
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Wait for DHCP and get DNS suffix at boot
### END INIT INFO

case "$1" in
    start)
        echo "Starting wait-for-dhcp..."
        /usr/bin/wait_for_dhcp.sh &
        echo "Starting get_dns_suffix script..."
        /usr/bin/get_dns_suffix.sh &
        ;;
    stop)
        echo "Stop action not implemented"
        exit 0
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

