#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          inetd
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the inetd daemon.
### END INIT INFO

if ! [ -x /usr/sbin/inetd ]; then
	exit 0
fi

case "$1" in
    start)
	echo -n "Starting internet superserver:"
	echo -n " inetd" ; start-stop-daemon -S -x /usr/sbin/inetd > /dev/null
	echo "."
	;;
    stop)
	echo -n "Stopping internet superserver:"
	echo -n " inetd" ; start-stop-daemon -K -x /usr/sbin/inetd > /dev/null
	echo "."
	;;
    restart)
	echo -n "Restarting internet superserver:"
	echo -n " inetd "
	killall -HUP inetd
	echo "."
	;;
    *)
	echo "Usage: /etc/init.d/inetd {start|stop|restart}"
	exit 1
	;;
esac

exit 0

