#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          telnetd
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the inetd daemon.
### END INIT INFO

if ! [ -x /usr/sbin/telnetd ]; then
	exit 0
fi

case "$1" in
    start)
	echo -n "Starting telnet server:"
	echo -n " telnetd" ; start-stop-daemon -S -x /usr/sbin/telnetd > /dev/null
	echo "."
	;;
    stop)
	echo -n "Stopping telnet server:"
	echo -n " telnetd" ; start-stop-daemon -K -x /usr/sbin/telnetd > /dev/null
	echo "."
	;;
    restart)
	echo -n "Restarting telnet server:"
	echo -n " telnetd "
	killall -HUP telnetd
	echo "."
	;;
    *)
	echo "Usage: /etc/init.d/telnetd {start|stop|restart}"
	exit 1
	;;
esac

exit 0

