diff -Naur a/Makefile b/Makefile
--- a/Makefile	2015-10-25 16:14:04.000000000 +0100
+++ b/Makefile	2016-02-21 22:45:33.605866815 +0100
@@ -15,7 +15,6 @@
 hidd-objs = \
 	hidd.o
 
-CFLAGS = -I. -Ilib -I${includedir}/glib-2.0 -I/usr/lib/glib-2.0/include -Wall
 
 all: hidd 
 
