--- a/Makefile	2017-12-13 15:14:14.000000000 +0100
+++ b/Makefile	2017-12-13 15:20:46.678844837 +0100
@@ -3,7 +3,7 @@
 
 INSTALL		= install -m 755
 INSTALL_DATA	= install -m 644
-DESTDIR		=
+DESTDIR		?=
 sbindir		= /sbin
 mandir		= /usr/share/man
 man8dir		= $(mandir)/man8
@@ -20,7 +20,7 @@
     COPTS      += -DUSE_BLOGD
 endif

-CC     = gcc
+CC     ?= gcc
 CFLAGS = $(RPM_OPT_FLAGS) $(COPTS) -D_GNU_SOURCE $(INC) -Wall -W -pipe

 # Enable large file support on GNU/Hurd
