#!/bin/sh

echo -n "Waiting for system to settle"
for i in 1 2 3 4 5 6 7 8 9 10;
do
	sleep 1
	echo -n "."
done          

# Remove package samba unless the user installed it manually
opkg info samba | grep Status: | grep -q user || opkg --force-depends remove samba

# Remove obsolete package sambaserver
opkg --force-depends remove sambaserver

[ -e /etc/samba/smb.conf-opkg ] && rm /etc/samba/smb.conf-opkg
[ -e /etc/samba/smb.conf ] && mv /etc/samba/smb.conf /etc/samba/smb.conf-user

PKGS=""
for PKG in cifs smbclient samba-base samba samba-advanced libsmbclient0 smbnetfs
do
	opkg list_installed ${PKG} | grep -q "-" && PKGS="${PKGS} ${PKG}"
done


opkg --force-depends remove $PKGS >/dev/null 2>&1

sleep 2
chattr -i /etc/init.d/samba
rm /etc/init.d/samba

opkg --force-reinstall install samba-base
for PKG in ${PKGS}
do
	opkg --force-reinstall install ${PKG}
done
opkg --force-reinstall install packagegroup-base-smbfs-server

update-rc.d -f samba-upgrade remove
rm /etc/init.d/samba-upgrade
exit 0
