#! /bin/sh 
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="upnp media server"
NAME=mediatomb
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/mediatomb
USER=root
GROUP=root
LOGFILE=/var/log/mediatomb
HOME=/hdd/mediatomb
INTERFACE=eth0

IF=`route -n | grep ^0.0.0.0 | awk {'print $8'}`
if ! grep -q down /sys/class/net/$IF/operstate; then
	INTERFACE=$IF
fi
	
D_ARGS="-c /etc/mediatomb/config.xml -d -u $USER -g $GROUP -m $HOME -P $PIDFILE -l $LOGFILE -e $INTERFACE"

if [ ! -e  "/hdd/mediatomb" ]; then
	mkdir -p /hdd/mediatomb
fi

test -x $DAEMON || exit 0

d_start() {
	touch $PIDFILE
	chown $USER:$GROUP $PIDFILE
	touch $LOGFILE
	chown $USER:$GROUP $LOGFILE
        start-stop-daemon --start --quiet --pidfile $PIDFILE \
                --exec $DAEMON -- $D_ARGS
}

d_stop() {
        start-stop-daemon --stop --signal 2 --retry 5 --quiet --pidfile $PIDFILE \
                --name $NAME
        rm $PIDFILE
}

case "$1" in
  start)
        echo -n "Starting $DESC: $NAME"
        d_start
        echo "."
        ;;
  stop)
        echo -n "Stopping $DESC: $NAME"
        d_stop
        echo "."
        ;;
  restart)
        echo -n "Restarting $DESC: $NAME"
        d_stop
        sleep 1
        d_start
        echo "."
        ;;
  *)

        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0