#!/bin/sh

# description: Startup/shutdown script for MiniDLNA daemon

MINIDLNA=/usr/sbin/minidlnad
PIDFILE=/var/run/minidlna/minidlna.pid
CONF=/etc/minidlna.conf
ARGS="-f $CONF"

test -f $MINIDLNA || exit 0

case "$1" in
	start)
		echo "Starting minidlna" "minidlna"
		start-stop-daemon --start --pidfile $PIDFILE --startas $MINIDLNA -- $ARGS
		echo "done"
		;;
	stop)
		echo "Stopping minidlna" "minidlna"
		start-stop-daemon --stop --pidfile $PIDFILE
		echo "done"
		;;
	restart|reload|force-reload)
		echo "Restarting minidlna" "minidlna"
		start-stop-daemon --stop --retry 5 --pidfile $PIDFILE
		sleep 5
		start-stop-daemon --start --pidfile $PIDFILE --startas $MINIDLNA -- $ARGS
		echo "done"
		;;
	*)
		echo "Usage: /etc/init.d/minidlna {start|stop|restart|reload|force-reload}"
		exit 1
		;;
esac

exit 0 
