#! /bin/sh
### BEGIN INIT INFO
# Provides:          bootlogd
# Required-Start:
# Required-Stop:
# Default-Start:     
# Default-Stop:      
# Short-Description: One of the first scripts to be executed. Starts or stops
#               the bootlogd log program. If this script is called as
#               "stop-bootlogd", it will stop the daemon instead of
#               starting it even when called with the "start" argument.
#
### END INIT INFO

exit 0
