#!/bin/sh

if ! test -e /.resizerootfs
then
    if grep -q mmcblk0p12 /proc/cmdline
    then
        echo "Resizing /dev/mmcblk0p12, Do not unplug power!..."
        resize2fs /dev/mmcblk0p12
        touch /.resizerootfs
    fi
    if grep -q mmcblk0p14 /proc/cmdline
    then
        echo "Resizing /dev/mmcblk0p14, Do not unplug power!..."
        resize2fs /dev/mmcblk0p14
        touch /.resizerootfs
    fi
fi

: exit 0
