#!/bin/sh

# Create display device if not present
if [ -e /dev/dbox/oled0 ] ; then
	ln -s /dev/dbox/oled0 /dev/vfd
fi

# Create hdmi cec device
if ! [ -e /dev/hdmi_cec ] ; then
        /bin/mknod /dev/hdmi_cec c 149 0
fi

# Flush eth0 device which is set by kernel cmdline
ip addr flush dev eth0 scope global
