# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*.bb ${LAYERDIR}/recipes-*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "vuplusde-layer"
BBFILE_PATTERN_vuplusde-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_vuplusde-layer = "7"

LAYERSERIES_COMPAT_vuplusde-layer = "wrynose blacksail"

OEA-META-VUPLUSDE-BASE := '${@os.path.normpath("${LAYERDIR}/")}'
