#! /bin/sh 

mkdir -p /dev/dvb /dev/pts /dev/dbox /dev/misc /dev/dvb/adapter0 /dev/loop /dev/i2c /dev/input /dev/sound /dev/fb /dev/vc /dev/mtdblock /dev/mtd /dev/tts

mknod /dev/tty0 c 4 0 
mknod /dev/tty1 c 4 1 
mknod /dev/tty2 c 4 2
mknod /dev/tty3 c 4 3

mknod /dev/watchdog c 10 130

mknod /dev/zero c 1 5

mknod /dev/sound/dsp c 14 3
mknod /dev/sound/mixer c 14 0
mknod /dev/sound/mixer1 c 14 16

#mknod /dev/dvb/adapter0/demux5 c 212 84
#mknod /dev/dvb/adapter0/demux6 c 212 100
#mknod /dev/dvb/adapter0/demux7 c 212 116 
#mknod /dev/dvb/adapter0/dvr5 c 212 85
#mknod /dev/dvb/adapter0/dvr6 c 212 101
#mknod /dev/dvb/adapter0/dvr7 c 212 117
#mknod /dev/dvb/adapter0/net5 c 212 87
#mknod /dev/dvb/adapter0/net6 c 212 103
#mknod /dev/dvb/adapter0/net7 c 212 119 

mknod /dev/input/mouse0 c 13 32

mknod /dev/i2c/0 c 89 0

mknod /dev/sci0 c 10 58
mknod /dev/ci0 c 213 0
 