require conf/machine/include/odin-oem.inc

SOC_FAMILY = "bcm7358"

RCTYPE = "504"
RCNAME = "e3hd"

# Broken bootloader can only flash around 100 MB
FLASHSIZE = "96"

PREFERRED_VERSION_linux-odin = "3.18.24"

MACHINE_FEATURES += " ubimb chkrootmb emmc videoenhancement smallflash blindscan-tbs RCA NO_SCART_SWITCH singlecore"
