# MACHINEBUILDS: axodin axodinc classm evo galaxym6 genius starsatlx
require conf/machine/include/odin-oem.inc

# Broken bootloader can only flash around 100 MB
FLASHSIZE = "96"

EXTRA_IMAGEDEPENDS += "\
    odin-backup \
    "

MACHINE_EXTRA_RDEPENDS = "\
    odin-backup \
    "

MACHINE_FEATURES += " ubimb chkrootmb emmc videoenhancement smallflash blindscan-tbs 7segment singlecore"

PREFERRED_VERSION_linux-odin = "3.18.24"

SOC_FAMILY = "bcm7358"

RCTYPE = "505"
RCNAME = "odinm7"
